### ISSUE TITLE
Configure more eslint rules

### ISSUE THREAD

**Issue by Jameskmonger** [Jameskmonger/modunit#10]
Here are some of the rules I'd like to see:

- http://eslint.org/docs/rules/comma-dangle
- http://eslint.org/docs/rules/no-cond-assign
- http://eslint.org/docs/rules/no-constant-condition
- http://eslint.org/docs/rules/no-dupe-args
- http://eslint.org/docs/rules/no-dupe-keys
- http://eslint.org/docs/rules/no-duplicate-case
- http://eslint.org/docs/rules/no-empty
- http://eslint.org/docs/rules/no-ex-assign
- http://eslint.org/docs/rules/no-eval

**Comment by Jameskmonger** [comment]
There are probably **lots** more good rules @SiAdcock - what do you recommend?

**Comment by SiAdcock** [comment]
We could extend `eslint:recommended` to cover a bunch of the most sensible ones. See everything with a :heavy_check_mark: in this list:

http://eslint.org/docs/rules/
